### ISSUE TITLE
Bild-Upload Tour und User

### ISSUE THREAD

**Issue by web17dennis** [web17dennis/myguide#8]

**Comment by web17dennis** [comment]
[https://www.w3schools.com/php/php_file_upload.asp](https://www.w3schools.com/php/php_file_upload.asp)

**Comment by danielhoover** [comment]
So, Herr Pockstaller,

nun kommen wir also zum Bildupload Problem.

Das Problem ist, dass Sie ja statt eines normalen Formulars das ganze über die Schnittstelle und JSON machen wollen. Insofern müssen wir ein paar Kleinigkeiten ändern, damit Sie im createRequest und saveRequest auch Daten in $_FILES haben. In includes/views/tour.php:

```javascript
      [...]
      if(!hasError)
        {
            var formData = new FormData(this);

            $.ajax({
                'url': $(this).attr('action'),
                'method': $(this).attr('method'),
                'data': formData,
                'contentType': false,
                'processData': false,
                'dataType': "json",
                'success': function (receivedData) {
      [...]
```

Das sollte es gewesen sein. Jetzt sollten die Daten wie gewünscht ankommen.

Probieren Sie das bitte mal und geben mir bescheid.

Herzliche Grüße
Daniel Hoover

**Comment by web17dennis** [comment]
Hallo Herr Hoover!

Die Schnittstelle meldet jetzt immer:
`{"result":false,"data":{"errorFields":{"name":"Bitte geben Sie einen Wert ein!","description":"Bitte geben Sie einen Wert ein!","regionid":"Bitte geben Sie einen Wert ein!","difficultyid":"Bitte geben Sie einen Wert ein!","ratingid":"Bitte geben Sie einen Wert ein!","activityid":"Bitte geben Sie einen Wert ein!"}}}`

Das Format der übermittelten Daten wird jetzt in den Entwicklertools so angezeigt - also kein JSON mehr:

------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="name"

Stripsenkopf über Stripsenjochhaus
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="date"

2016-04-03
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="ratingid"

1
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="regionid"

1
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="startlocation"

Griesneralm Kaiserbachtal 6b, 6382 - Kirchdorf in Tirol
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="activityid"

1
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="difficultyid"

1
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="duration"

05:00:00
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="description"

Aussichtsreicher Höhenweg über Feldberg und Stripsenjoch: Auf dem Stripsenjoch begegnen sich die Welten der Wanderer und Kletterer – für die einen das lohnende Ziel nach mühevollem Anstieg für, die anderen Ausgangspunkt in die berühmten Kletterwände von Fleischbank und Totenkirchl. Die aussichtsreiche Kammwanderung gegenüber den Gipfeln des Wilden Kaisers lässt sich als Panoramaplatz kaum überbieten. Lärchegg, Predigtstuhl, Fleischbank und Totenkirchl, getrennt von mächtigen Karen, zeigen sich von ihrer schönsten und wildesten Seite. Wie ein Adlerhorst schmiegt sich das Stripsenjochaus an den Fuß des Totenkirchls. Im Kontrast dazu reicht die Fernsicht bis ins bayrische Alpenvorland mit dem Chiemsee. Es gibt eine Qualität der Zeit und eine Qualität des Ortes, wenn beide Zusammentreffen fühlen sich Menschen glücklich berührt. Ein Sonnenuntergang am Tavonaro Kreuz, mit dem Naturschauspiel der rosa leuchtenden Felsendome könnte so ein Augenblick sein.
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="fileToUpload"; filename="myguide-er-modell-v1.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="image"

wanderung1.jpg
------WebKitFormBoundaryBdIGo6VXHKqi4v3k
Content-Disposition: form-data; name="id"

1
------WebKitFormBoundaryBdIGo6VXHKqi4v3k--


Beste Grüße
Dennis

**Comment by web17dennis** [comment]
Hallo Herr Hoover!

Long story short: es läuft jetzt!
Vielen Dank für Ihre Hilfe!

Hier einige der Anpassungen, die ich vornehmen musste:

1. Da $_FILES aus Ihrem Beispiel nicht an den Restservice Tour.php mitgesendet wird, habe ich die Variable $data in api.php einfach so angepasst, dass die Werte vom Bild wie folgt zusätzlich in $data gespeichert werden:

Array
(
    [name] => Stripsenkopf über Stripsenjochhaus
    [date] => 2016-04-03
    [ratingid] => 1
    [regionid] => 1
    [startlocation] => Griesneralm Kaiserbachtal 6b, 6382 - Kirchdorf in Tirol
    [activityid] => 1
    [difficultyid] => 1
    [duration] => 05:00:00
    [description] => description blabla
    [image] => wanderung1.jpg
    [id] => 1
    [file] => Array
        (
            [name] => Array
                (
                    [0] => testbild.jpg
                )
            [type] => Array
                (
                    [0] => image/jpeg
                )
            [tmp_name] => Array
                (
                    [0] => /tmp/php8450e4
                )
            [error] => Array
                (
                    [0] => 0
                )
            [size] => Array
                (
                    [0] => 39457
                )
        )
)

2. move_uploaded_file() in Tour.php funktionierte in diesem Szenario nicht, daher durch rename() ersetzt.

3. Da Stream.php die Werte in weitere Unter-Arrays speichert, greife ich so auf die Daten zu: $data['file']["name"][0]
Das könnte man auch über reset() lösen.
Vermutlich kann man über die Unter-Arrays mehrere Dateien gleichzeitig behandeln, was wir aber nicht benötigen.

4. Irgendwo im Verlauf des Uploads werden 2 unnötige Zeilenumbrüche in den head von Bildern geschrieben, welche verhindern, dass man die Bilder ansehen kann. Diese entferne ich unter Zeile 154 in Tour.php wieder.

Alles in allem eine ziemlich gebastelte und unsaubere Lösung, aber für unser Projekt sollte es zumindest ausreichend sein.
Nachdem ich nun ziemlich lange daran gebastelt habe, habe ich keine Zeit mehr um das ganze noch für POST anzupassen. Das Feld Bildupload ist jetzt im Erstellen-Formular ausgeblendet. Wenn man ein Bild hinzufügen will, muss man die Tour bearbeiten.
Auch die Behandlung von Fehlern beim Upload, wie zum Beispiel gleiche Dateinamen usw. ist noch nicht fertig. 

Vielen Dank nochmals! Schönes Wochenende und beste Grüße,
Dennis

**Comment by danielhoover** [comment]
Das haben Sie sehr gut gemacht Herr Pockstaller!

In der Praxis würde man es vermutlich so machen, dass der Bildupload ein eigener REST Service ist. (und nicht eben auch noch andere Daten entgegennimmt) Das bedingt natürlich, dass das Element zu dem ein Bild hinzugefügt werden soll bereits in der Tabelle vorhanden ist. (also vorher angelegt wurde) Diesen eigenen REST Service hätte man auch so gestalten können, dass der Bildupload wie gewohnt über POST läuft und somit alles so ist wie es in PHP bekannt ist. Alternativ nutzt man (insbesondere bei möglicherweise zu großen Bildern) eine Library die einem das ganze clientseitig kleiner rechnet und auch stückweise überträgt. (so wie man es bei ftp kennt) [plupload](https://www.plupload.com/) ist ein Beispiel im Zusammenhang mit PHP.

Das aber nur als ergänzender Hinweis. Das das Bild hinzufügen also "nur" beim speichern funktioniert ist überhaupt kein Problem. (auch aus konzeptioneller Sicht) Ich denke, dass Sie damit mehr als ausreichend zu tun gehabt haben. Sie haben die "4 Personen im Team"-Extra Aufgabe also sehr gut gelöst - soviel sei Ihnen schon mal verraten.
